<h2>FAQ</h2> 
<div id="tabs"> 
  <ul> 
    <li><a href="#tabs-1">How can I download eBooks?</a></li> 
    <li><a href="#tabs-2">What payment methods can I use?</a></li> 
    <li><a href="#tabs-3">What format are Bookstore eBooks?</a></li> 
  </ul> 
  <div id="tabs-1"> 
    <p>Once you complete your eBook purchase, the download link for your eBook will be available in your account.</p> 
  </div> 
  <div id="tabs-2"> 
    <p>You can pay with the following card types: 
      <ol> 
        <li>Visa Debit</li> 
        <li>Visa Credit</li> 
        <li>MasterCard</li> 
        <li>PayPal</li> 
        <li>American Express</li> 
      </ol> 
    </p> 
  </div> 
  <div id="tabs-3"> 
    <p>Bookstore eBooks can be downloaded as a PDF, EPUB or MOBI file. They can also be viewed online.</p> 
  </div> 
</div> 

<ul class="bxslider">
  <li><img src="http://bxslider.com/images/home_slides/picto.png" /></li>
  <li><img src="http://bxslider.com/images/home_slides/picto.png" /></li>
  <li><img src="http://bxslider.com/images/home_slides/picto.png" /></li>
  <li><img src="http://bxslider.com/images/home_slides/picto.png" /></li>
</ul>
 
<script> 
require(['jquery','jquery/ui', 'jqueryBxslider'],function($){
  $("#tabs").tabs();
  $(".bxslider").bxSlider();
});
</script>